### ISSUE TITLE
Encourage people to get a BCI printout.

### ISSUE THREAD

**Issue by joeldenning** [UtahAccessToJustice/utahexpungements.org#17]
https://bci.utah.gov/wp-content/uploads/sites/15/2018/01/ROA-12-5-2017.pdf

$15

15-20 mins

**Comment by leahjlou** [comment]
Added a banner to the eligibility tool

![screen shot 2018-10-30 at 6 47 35 am](https://user-images.githubusercontent.com/2423414/47719097-ba1ec900-dc0f-11e8-8c33-e7544fde0af8.png)
