### ISSUE TITLE
Make the footer always at the bottom of the page

### ISSUE THREAD

**Issue by joeldenning** [UtahAccessToJustice/utahexpungements.org#9]
I don't think the header should be fixed positioned, because we don't want it to always show. And I don't think that we need to do fancy stickiness for the footer or anything. But we just need to make sure that on big screens or pages with not a lot of content that the footer is never above the bottom of the page.

**Comment by lukeschunk** [comment]
fixed here: https://github.com/UtahAccessToJustice/utahexpungements.org/commit/c7d6c060e0254f897b2821de549554ac753ea53e
